stages:
    - source
    - build
    - deploy

portable-source:
    stage: source
    tags:
        - graphviz,centos7
    script:
        - ./autogen.sh
        - make dist
    artifacts:
        when: on_success
        expire_in: 1 week
        paths:
            - VERSION
            - COLLECTION
            - graphviz-*.tar.gz
    only:
        - master

.build_template: &rpm_build_definition
    stage: build
    script:
        - rm -rf /home/gitlab-runner/rpmbuild
        - VERSION=$( cat VERSION )
        - rpmbuild -ta graphviz-${VERSION}.tar.gz
        - eval $( grep VERSION_ID /etc/os-release )
        - eval $( grep NAME /etc/os-release )
        - ARCH=$( uname -m )
        - DIR=Packages/${NAME}/${VERSION_ID}
        - mkdir -p ${DIR}/os/${ARCH}
        - mkdir -p ${DIR}/debug/${ARCH}
        - mkdir -p ${DIR}/source
        - mv /home/gitlab-runner/rpmbuild/SRPMS/*.src.rpm ${DIR}/source/
        - mv /home/gitlab-runner/rpmbuild/RPMS/*/*debuginfo*rpm ${DIR}/debug/${ARCH}/
        - mv /home/gitlab-runner/rpmbuild/RPMS/*/*.rpm ${DIR}/os/${ARCH}/
    artifacts:
        when: on_success
        expire_in: 1 week
        paths:
            - Packages/*/*/*/*
    only:
         - master

.build_template: &deb_build_definition
    stage: build
    script:
        - VERSION=$( cat VERSION )
        - zcat graphviz-${VERSION}.tar.gz | tar xf -
        - (cd graphviz-${VERSION}; fakeroot make -f debian/rules binary)
        - eval $( grep VERSION_ID /etc/os-release )
        - eval $( grep NAME /etc/os-release )
        - ARCH=$( uname -m )
        - DIR=Packages/${NAME}/${VERSION_ID}
        - mkdir -p ${DIR}/os/${ARCH}
        - mkdir -p ${DIR}/debug/${ARCH}
        - mkdir -p ${DIR}/source
        - mv *.deb ${DIR}/os/${ARCH}/
        - mv *.ddeb ${DIR}/debug/${ARCH}/
        - cp graphviz-${VERSION}.tar.gz ${DIR}/source/
    artifacts:
        when: on_success
        expire_in: 1 week
        paths:
            - Packages/*/*/*/*
    only:
        - master

centos6-build:
    <<: *rpm_build_definition
    tags:
        - graphviz,centos6

centos7-build:
    <<: *rpm_build_definition
    tags:
        - graphviz,centos7

fedora27-build:
    <<: *rpm_build_definition
    tags:
        - graphviz,fedora27

fedora28-build:
    <<: *rpm_build_definition
    tags:
        - graphviz,fedora28

fedora29-build:
    <<: *rpm_build_definition
    tags:
        - graphviz,fedora29

fedora30-build:
    <<: *rpm_build_definition
    tags:
        - graphviz,fedora30

fedora31-build:
    <<: *rpm_build_definition
    tags:
        - graphviz,fedora31

ubuntu18-04-build:
    <<: *deb_build_definition
    tags:
        - graphviz,ubuntu18-04

ubuntu18-10-build:
    <<: *deb_build_definition
    tags:
        - graphviz,ubuntu18-10

ubuntu19-04-build:
    <<: *deb_build_definition
    tags:
        - graphviz,ubuntu19-04


deployment:
    stage: deploy
    script:
        - uname -a
        - COLLECTION=$( cat COLLECTION )
        - ls -l
        - eval $(ssh-agent -s)
        - cat "$DEPLOY_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
        - mkdir -p ~/.ssh
        - chmod 700 ~/.ssh
        - ssh-keyscan "$DEPLOY_HOST" >> ~/.ssh/known_hosts
        - chmod 644 ~/.ssh/known_hosts
        - scp -r Packages "$DEPLOY_USER"@"$DEPLOY_HOST"

