stages:
    - source
    - build

portable-source-packaging:
    stage: source
    tags:
        - graphviz,centos7
    script:
        - ./autogen.sh
        - make dist
    artifacts:
        when: on_success
        expire_in: 1 week
        paths:
            - VERSION
            - graphviz-*.tar.gz
    only:
        - master

centos7-binary-packaging:
    stage: build
    tags:
        - graphviz,centos7
    script:
        - VERSION=$( cat VERSION )
        - rpmbuild -ta graphviz-$VERSION.tar.gz
    artifacts:
        when: on_success
        expire_in: 1 week
        paths:
            - graphviz-*.rpm
    only:
        - master
