version: 2.39.{build}

image: Visual Studio 2015

build:
  project: graphviz.sln
  verbosity: detailed

before_build:
  # Install GTK
  - C:\cygwin\setup-x86.exe -qnNdO -R C:/%cygwin% -s http://cygwin.mirror.constant.com -l C:/%cygwin%/var/cache/setup -P libgtk2.0_0 -P libgtk2.0-devel
  - set PATH=%PATH%;C:\cygwin\bin;C:\cygwin\lib
  - cp windows/config.h config.h
