version: 2.41.{build}

image: Visual Studio 2015

environment:
  matrix:
    - build_system: msbuild
    - build_system: cmake

configuration:
  - Debug
  - Release

install:
  # Retrieve submodules, dependencies are stored there.
  - git submodule update --init

before_build:
# This file is deleted to reduce noise in the build output. Otherwise several
# "target does not exist and will be ignored" messages are printed.
- del "C:\Program Files (x86)\MSBuild\14.0\Microsoft.Common.targets\ImportAfter\Xamarin.Common.targets"

build_script:
  - ps: >-
      cd $env:APPVEYOR_BUILD_FOLDER

      if($env:build_system -eq "msbuild") {
        $env:Path += ";" + $env:APPVEYOR_BUILD_FOLDER + "\windows\dependencies\graphviz-build-utilities";
        msbuild /p:Configuration=$env:configuration;
        if($env:configuration -eq "Release") {
          rm Release\Graphviz\bin\*.lastcodeanalysissucceeded;
          rm Release\Graphviz\bin\*.iobj;
          rm Release\Graphviz\bin\*.ipdb;
          rm Release\Graphviz\bin\*.ilk;
        }

        # Append build destination to the PATH, configure dot and execute regression tests
        $env:Path += ";" + $env:APPVEYOR_BUILD_FOLDER + "\" + $env:configuration + "\Graphviz\bin";
        dot -c;
        cd tests\regression_tests;
        ./regression_tests.bat;
      }

      if($env:build_system -eq "cmake") {
        $env:Path += ";" + $env:APPVEYOR_BUILD_FOLDER + "\windows\dependencies\graphviz-build-utilities";
        mkdir build;
        cd build;
        cmake ..;
        cmake --build . --config $env:configuration;
        if($env:configuration -eq "Release") {
          cpack;
        }
      }

artifacts:
  - path: Release
    name: graphviz-windows
  - path: Debug
    name: graphviz-windows-debug
