version: 2.41.{build}

image: Visual Studio 2015

environment:
  matrix:
    - build_system: msbuild
    - build_system: cmake

configuration:
  - Debug
  - Release

install:
  # Retrieve submodules, dependencies are stored there.
  - git submodule update --init

before_build:
# This file is deleted to reduce noise in the build output. Otherwise several
# "target does not exist and will be ignored" messages are printed.
- del "C:\Program Files (x86)\MSBuild\14.0\Microsoft.Common.targets\ImportAfter\Xamarin.Common.targets"

build_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - set PATH=%PATH%;%APPVEYOR_BUILD_FOLDER%\windows\dependencies\graphviz-build-utilities

  # Build
  - ps: >-
      if($env:build_system -eq "cmake") {
        mkdir build;
        cd build;
        cmake ..;
        cmake --build . --config $env:configuration;
      }
      elseif($env:build_system -eq "msbuild") {
        msbuild /p:Configuration=$env:configuration
      }

  # Package
  - ps: >-
      if($env:configuration -eq "Release") {
        if($env:build_system -eq "cmake") {
          cpack
        }
        elseif($env:build_system -eq "msbuild") {
          rm Release\Graphviz\bin\*.lastcodeanalysissucceeded;
          rm Release\Graphviz\bin\*.iobj;
          rm Release\Graphviz\bin\*.ipdb;
          rm Release\Graphviz\bin\*.ilk;
        }
      }

  # Test
  - ps: >-
      if($env:build_system -eq "cmake") {
        # No tests yet
      }
      elseif($env:build_system -eq "msbuild") {
        # Append build destination to the PATH, configure dot and execute regression tests
        $env:Path += ";" + $env:APPVEYOR_BUILD_FOLDER + "\" + $env:configuration + "\Graphviz\bin";
        dot -c;
        cd tests\regression_tests;
        ./regression_tests.bat;
      }

artifacts:
  - path: Release
    name: graphviz-windows
  - path: Debug
    name: graphviz-windows-debug
