version: 2.39.{build}

image: Visual Studio 2015

build:
  project: graphviz.sln
  verbosity: detailed

before_build:
  - ps: cp windows/config.h config.h
  - ps: 'C:\MinGW\bin\mingw-get install gtk2'
  - ps: set PATH=%PATH%;C:\MinGW\mingw
